{% set name = "cwcwidth" %}
{% set version = "0.1.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cwcwidth-{{ version }}.tar.gz
  sha256: 594d8855a6319cc3ef36e0b6374fae02e4f4fe17cd87d0debe8b6e00eb186c17

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - setuptools
    - python
    - cython >=0.28
  run:
    - python

test:
  imports:
    - cwcwidth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sebastinas/cwcwidth
  summary: Python bindings for wc(s)width
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - holymonson
    - mariusvniekerk
