{% set name = "cwcwidth" %}
{% set version = "0.1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cwcwidth-{{ version }}.tar.gz
  sha256: 5adc034b7c90e6a8586bd046bcbf6004e35e16b0d7e31de395513a50d729bbf6

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython >=0.28
  run:
    - python

test:
  imports:
    - cwcwidth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sebastinas/cwcwidth
  summary: Python bindings for wc(s)width
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - holymonson
    - mariusvniekerk
